### ISSUE TITLE
Is nuclear gradient supported with ECP?

### ISSUE THREAD

**Issue by awhite862** [pyscf/pyscf#671]
Is the molecular nuclear gradient supported with ECPs? The calculation runs, but the gradients don't match those obtained with finite difference.

**Comment by fishjojo** [comment]
Yes, ecp gradient is implemented. I tested it and there seems no problem.
When you do finite difference, did you check that the units are correct? The output gradient is in a.u.

**Comment by awhite862** [comment]
The units should be correct. It agrees without the ecp:

```
import copy
from pyscf import gto, scf, cc

ecp = {'Na':'lanl2dz', 'Cl' : 'lanl2dz'}
#ecp = None

def rhf_energy(atom):
    mol = gto.M(
        atom = atom,
        basis = 'lanl2dz',
        ecp = ecp, unit='B', verbose=0)
    mf = scf.RHF(mol)
    mf.conv_tol_grad = 1e-9
    E = mf.kernel()
    return E

atom = [        
        ['Na',  0.00,  0.00,   0.000000000000],
        ['Cl',  0.00,  0.00,   2.050000000000]]
mol = gto.M(
    atom = atom,
    basis = 'lanl2dz',
    ecp = ecp, unit='B')

mf = scf.RHF(mol)
mf.kernel()
g = mf.nuc_grad_method()
g.kernel()

fd_grad = []
delta = 0.001
for i,x in enumerate(atom):
    xgrad = 3*[None]
    for dim in [0,1,2]:
        temp = copy.deepcopy(atom)
        temp[i][dim + 1] += delta
        f = rhf_energy(temp)
        temp = copy.deepcopy(atom)
        temp[i][dim + 1] -= delta
        b = rhf_energy(temp)
        xgrad[dim] = (f - b)/(2*delta)
    fd_grad.append(xgrad)



print("--------------- RHF FD gradient ---------------")
print("       x               y               z ")
for i,x in enumerate(fd_grad):
    print(" {}: {:13.10f}   {:13.10f}   `{:13.10f}".format(i,x[0],x[1],x[2]))`
```

**Comment by sunqm** [comment]
Bug fixed in pyscf-1.7.4 or higher

**Comment by awhite862** [comment]
This issue is still not fixed for me in pyscf-1.7.4. The script I posted above still fails as do the added ecp tests in pyscf/gto/test

**Comment by awhite862** [comment]
Nevermind, it's fixed now, thanks!
